export const PRIVACY_POLICY = `
## 1\. Introduction

Welcome to **SVR.JS**.

**SVR.JS** ("us", "we", or "our") operates **svrjs.org** (hereinafter referred to as **"Service"**).

Our Privacy Policy governs your visit to **svrjs.org**, and explains how we collect, safeguard and disclose information that results from your use of our Service.

We use your data to provide and improve Service. By using Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions.

Our Terms and Conditions (**"Terms"**) govern all use of our Service and together with the Privacy Policy constitutes your agreement with us (**"agreement"**).

## 2\. Definitions

**SERVICE** means the svrjs.org website operated by SVR.JS.

**PERSONAL DATA** means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).

**USAGE DATA** is data collected automatically either generated by the use of Service or from Service infrastructure itself (for example, the duration of a page visit).

**COOKIES** are small files stored on your device (computer or mobile device).

**DATA CONTROLLER** means a natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal data are, or are to be, processed. For the purpose of this Privacy Policy, we are a Data Controller of your data.

**DATA PROCESSORS (OR SERVICE PROVIDERS)** means any natural or legal person who processes the data on behalf of the Data Controller. We may use the services of various Service Providers in order to process your data more effectively.

**DATA SUBJECT** is any living individual who is the subject of Personal Data.

**THE USER** is the individual using our Service. The User corresponds to the Data Subject, who is the subject of Personal Data.

## 3\. Information Collection and Use

We collect several different types of information for various purposes to provide and improve our Service to you.

## 4\. Types of Data Collected

### Personal Data

While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you (**"Personal Data"**). Personally identifiable information may include, but is not limited to:

1. Email address

We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link.

### Usage Data

We may collect information that your browser sends whenever you visit our Service or when you access Service by or through any device (**"Usage Data"**).

This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, and other diagnostic data.

When you access Service with a device, this Usage Data may include information such as the type of device you use, the IP address of your device, your device operating system, the type of Internet browser you use and other diagnostic data.

### Tracking Cookies Data

We don't use any cookies for tracking on our Service. You can however set a cookie that allows opt-out from Matomo analytics using form in the Section 14.

## 5\. Use of Data

SVR.JS uses the collected data for various purposes:

1.  to provide and maintain our Service;
2.  to allow you to participate in interactive features of our Service when you choose to do so;
3.  to provide customer support;
4.  to gather analysis or valuable information so that we can improve our Service;
5.  to monitor the usage of our Service;
6.  to detect, prevent and address technical issues;
7.  to fulfil any other purpose for which you provide it;
8.  in any other way we may describe when you provide the information;
9.  for any other purpose with your consent.

## 6\. Retention of Data

We will retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods.

## 7\. Transfer of Data

Your information, may be transferred to – and maintained on – computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.

If you are located outside Poland and choose to provide information to us, please note that we transfer the data, to Poland and process it there.

Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.

SVR.JS will take all the steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your data will take place to an organisation or a country unless there are adequate controls in place including the security of your data and other personal information.

## 8\. Disclosure of Data

We don't disclose any information that we collect.

## 9\. Security of Data

The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.

## 10\. Your Data Protection Rights Under General Data Protection Regulation (GDPR)

If you are a resident of the European Union (EU) and European Economic Area (EEA), you have certain data protection rights, covered by GDPR.

We aim to take reasonable steps to allow you to correct, amend, delete, or limit the use of your Personal Data.

If you wish to be informed what Personal Data we hold about you and if you want it to be removed from our systems, please email us at _privacy@svrjs.org_.

In certain circumstances, you have the following data protection rights:

1.  the right to access, update or to delete the information we have on you;
2.  the right of rectification. You have the right to have your information rectified if that information is inaccurate or incomplete;
3.  the right to object. You have the right to object to our processing of your Personal Data;
4.  the right of restriction. You have the right to request that we restrict the processing of your personal information;
5.  the right to data portability. You have the right to be provided with a copy of your Personal Data in a structured, machine-readable and commonly used format;
6.  the right to withdraw consent. You also have the right to withdraw your consent at any time where we rely on your consent to process your personal information;

Please note that we may ask you to verify your identity before responding to such requests. Please note, we may not able to provide Service without some necessary data.

You have the right to complain to a Data Protection Authority about our collection and use of your Personal Data. For more information, please contact your local data protection authority in the European Economic Area (EEA).

## 11\. Your Data Protection Rights under the California Privacy Protection Act (CalOPPA)

CalOPPA is the first state law in the nation to require commercial websites and online services to post a privacy policy. The law's reach stretches well beyond California to require a person or company in the United States (and conceivable the world) that operates websites collecting personally identifiable information from California consumers to post a conspicuous privacy policy on its website stating exactly the information being collected and those individuals with whom it is being shared, and to comply with this policy.

According to CalOPPA we agree to the following:

1.  users can visit our site anonymously;
2.  our Privacy Policy link includes the word "Privacy", and can easily be found on the home page of our website;
3.  users will be notified of any privacy policy changes on our Privacy Policy Page;
4.  users are able to change their personal information by emailing us at _privacy@svrjs.org_.

## 12\. Your Data Protection Rights under the California Consumer Privacy Act (CCPA)

If you are a California resident, you are entitled to learn what data we collect about you, ask to delete your data and not to sell (share) it. To exercise your data protection rights, you can make certain requests and ask us:

**What personal information we have about you. If you make this request, we will return to you:**

1.  The categories of personal information we have collected about you.
2.  The categories of sources from which we collect your personal information.
3.  The business or commercial purpose for collecting or selling your personal information.
4.  The categories of third parties with whom we share personal information.
5.  The specific pieces of personal information we have collected about you.
6.  A list of categories of personal information that we have sold, along with the category of any other company we sold it to. If we have not sold your personal information, we will inform you of that fact.
7.  A list of categories of personal information that we have disclosed for a business purpose, along with the category of any other company we shared it with.

Please note, you are entitled to ask us to provide you with this information up to two times in a rolling twelve-month period. When you make this request, the information provided may be limited to the personal information we collected about you in the previous 12 months.

-  **To delete your personal information. If you make this request, we will delete the personal information we hold about you as of the date of your request from our records and direct any service providers to do the same. In some cases, deletion may be accomplished through de-identification of the information. If you choose to delete your personal information, you may not be able to use certain functions that require your personal information to operate.**
-  **To stop selling your personal information. We don't sell or rent your personal information to any third parties for any purpose. We do not sell your personal information for monetary consideration. However, under some circumstances, a transfer of personal information to a third party, or within our family of companies, without monetary consideration may be considered a "sale" under California law. You are the only owner of your Personal Data and can request disclosure or deletion at any time.**

If you submit a request to stop selling your personal information, we will stop making such transfers.

Please note, if you ask us to delete or stop selling your data, it may impact your experience with us, and you may not be able to participate in certain programs or membership services which require the usage of your personal information to function. But in no circumstances, we will discriminate against you for exercising your rights.

To exercise your California data protection rights described above, please send your request(s) by email: _privacy@svrjs.org_.

Your data protection rights, described above, are covered by the CCPA, short for the California Consumer Privacy Act. To find out more, visit the official California Legislative Information website. The CCPA took effect on 01.01.2020.

## 13\. Service Providers

We may employ third party companies and individuals to facilitate our Service (**"Service Providers"**), provide Service on our behalf, perform Service-related services or assist us in analysing how our Service is used.

These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.

## 14\. Analytics

We are using a self-hosted Matomo instance at _analytics.svrjs.org_ to monitor and analyze the use of our Service.

You may choose to prevent this website from aggregating and analyzing the actions you take here. Doing so will protect your privacy, but will also prevent the owner from learning from your actions and creating a better experience for you and other users. You can visit the [opt-out form there](https://analytics.svrjs.org/index.php?module=CoreAdminHome&action=optOut&language=en-US).

## 15\. CI/CD tools

We may use third-party Service Providers to automate the development process of our Service.

## 16\. Behavioral Remarketing

We may use remarketing services to advertise on third party websites to you after you visited our Service. We and our third-party vendors use cookies to inform, optimise and serve ads based on your past visits to our Service.

## 17\. Links to Other Sites

Our Service may contain links to other sites that are not operated by us. If you click a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit.

We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.

## 18\. Children's Privacy

Our Services are not intended for use by children under the age of 18 (**"Child"** or **"Children"**).

We do not knowingly collect personally identifiable information from Children under 18\. If you become aware that a Child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from Children without verification of parental consent, we take steps to remove that information from our servers.

## 19\. Changes to This Privacy Policy

We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.

We will let you know via a prominent notice on our Service, prior to the change becoming effective and update "effective date" at the top of this Privacy Policy.

You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.

## 20\. Contact Us

If you have any questions about this Privacy Policy, please contact us by email: _privacy@svrjs.org_.
`;

export const TERMS_AND_CONDITIONS = `
## 1\. Introduction

Welcome to **SVR.JS** ("Company", "we", "our", "us")!

These Terms of Service ("Terms", "Terms of Service") govern your use of our website located at **svrjs.org** (together or individually "Service") operated by **SVR.JS**.

Our Privacy Policy also governs your use of our Service and explains how we collect, safeguard and disclose information that results from your use of our web pages.

Your agreement with us includes these Terms and our Privacy Policy ("Agreements"). You acknowledge that you have read and understood Agreements, and agree to be bound of them.

If you do not agree with (or cannot comply with) Agreements, then you may not use the Service, but please let us know by emailing at _support@svrjs.org_ so we can try to find a solution. These Terms apply to all visitors, users and others who wish to access or use Service.

## 2\. Content

Content found on or through this Service are the property of SVR.JS or used with permission. You may not distribute, modify, transmit, reuse, download, repost, copy, or use said Content, whether in whole or in part, for commercial purposes or for personal gain, unless stated otherwise.

## 3\. Prohibited Uses

You may use Service only for lawful purposes and in accordance with Terms. You agree not to use Service:

1.  In any way that violates any applicable national or international law or regulation.
2.  For the purpose of exploiting, harming, or attempting to exploit or harm minors in any way by exposing them to inappropriate content or otherwise.
3.  To transmit, or procure the sending of, any advertising or promotional material, including any "junk mail", "chain letter," "spam," or any other similar solicitation.
4.  To impersonate or attempt to impersonate Company, a Company employee, another user, or any other person or entity.
5.  In any way that infringes upon the rights of others, or in any way is illegal, threatening, fraudulent, or harmful, or in connection with any unlawful, illegal, fraudulent, or harmful purpose or activity.
6.  To engage in any other conduct that restricts or inhibits anyone's use or enjoyment of Service, or which, as determined by us, may harm or offend Company or users of Service or expose them to liability.

Additionally, you agree not to:

1.  Use Service in any manner that could disable, overburden, damage, or impair Service or interfere with any other party's use of Service, including their ability to engage in real time activities through Service.
2.  Use any robot, spider, or other automatic device, process, or means to access Service for any purpose, including monitoring or copying any of the material on Service.
3.  Use any manual process to monitor or copy any of the material on Service or for any other unauthorized purpose without our prior written consent.
4.  Use any device, software, or routine that interferes with the proper working of Service.
5.  Introduce any viruses, trojan horses, worms, logic bombs, or other material which is malicious or technologically harmful.
6.  Attempt to gain unauthorized access to, interfere with, damage, or disrupt any parts of Service, the server on which Service is stored, or any server, computer, or database connected to Service.
7.  Attack Service via a denial-of-service attack or a distributed denial-of-service attack.
8.  Take any action that may damage or falsify Company rating.
9.  Otherwise attempt to interfere with the proper working of Service.

## 4\. Analytics

We may use third-party Service Providers to monitor and analyze the use of our Service.

## 5\. Intellectual Property

Service and its original content (excluding Content provided by users), features and functionality are and will remain the exclusive property of SVR.JS and its licensors. Service is protected by copyright, trademark, and other laws of and foreign countries. Our trademarks may not be used in connection with any product or service without the prior written consent of SVR.JS.

## 6\. Copyright Policy

We respect the intellectual property rights of others. It is our policy to respond to any claim that Content posted on Service infringes on the copyright or other intellectual property rights ("Infringement") of any person or entity.

If you are a copyright owner, or authorized on behalf of one, and you believe that the copyrighted work has been copied in a way that constitutes copyright infringement, please submit your claim via email to _support@svrjs.org_, with the subject line: "Copyright Infringement" and include in your claim a detailed description of the alleged Infringement as detailed below, under "DMCA Notice and Procedure for Copyright Infringement Claims"

You may be held accountable for damages (including costs and attorneys' fees) for misrepresentation or bad-faith claims on the infringement of any Content found on and/or through Service on your copyright.

## 7\. DMCA Notice and Procedure for Copyright Infringement Claims

You may submit a notification pursuant to the Digital Millennium Copyright Act (DMCA) by providing our Copyright Agent with the following information in writing (see 17 U.S.C 512(c)(3) for further detail):

1.  an electronic or physical signature of the person authorized to act on behalf of the owner of the copyright's interest;
2.  a description of the copyrighted work that you claim has been infringed, including the URL (i.e., web page address) of the location where the copyrighted work exists or a copy of the copyrighted work;
3.  identification of the URL or other specific location on Service where the material that you claim is infringing is located;
4.  your address, telephone number, and email address;
5.  a statement by you that you have a good faith belief that the disputed use is not authorized by the copyright owner, its agent, or the law;
6.  a statement by you, made under penalty of perjury, that the above information in your notice is accurate and that you are the copyright owner or authorized to act on the copyright owner's behalf.

You can contact our Copyright Agent via email at _dorian.niemiec@svrjs.org_.

## 8\. Error Reporting and Feedback

You may provide us either directly at _support@svrjs.org_ or via third party sites and tools with information and feedback concerning errors, suggestions for improvements, ideas, problems, complaints, and other matters related to our Service ("Feedback"). You acknowledge and agree that: (i) you shall not retain, acquire or assert any intellectual property right or other right, title or interest in or to the Feedback; (ii) Company may have development ideas similar to the Feedback; (iii) Feedback does not contain confidential information or proprietary information from you or any third party; and (iv) Company is not under any obligation of confidentiality with respect to the Feedback. In the event the transfer of the ownership to the Feedback is not possible due to applicable mandatory laws, you grant Company and its affiliates an exclusive, transferable, irrevocable, free-of-charge, sub-licensable, unlimited and perpetual right to use (including copy, modify, create derivative works, publish, distribute and commercialize) Feedback in any manner and for any purpose.

## 9\. Links To Other Web Sites

Our Service may contain links to third party web sites or services that are not owned or controlled by SVR.JS.

SVR.JS has no control over, and assumes no responsibility for the content, privacy policies, or practices of any third party web sites or services. We do not warrant the offerings of any of these entities/individuals or their websites.

**<u>YOU ACKNOWLEDGE AND AGREE THAT COMPANY SHALL NOT BE RESPONSIBLE OR LIABLE, DIRECTLY OR INDIRECTLY, FOR ANY DAMAGE OR LOSS CAUSED OR ALLEGED TO BE CAUSED BY OR IN CONNECTION WITH USE OF OR RELIANCE ON ANY SUCH CONTENT, GOODS OR SERVICES AVAILABLE ON OR THROUGH ANY SUCH THIRD PARTY WEB SITES OR SERVICES.</u>**

**<u>WE STRONGLY ADVISE YOU TO READ THE TERMS OF SERVICE AND PRIVACY POLICIES OF ANY THIRD PARTY WEB SITES OR SERVICES THAT YOU VISIT.</u>**

## 10\. Disclaimer Of Warranty

**<u>THESE SERVICES ARE PROVIDED BY COMPANY ON AN "AS IS" AND "AS AVAILABLE" BASIS. COMPANY MAKES NO REPRESENTATIONS OR WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, AS TO THE OPERATION OF THEIR SERVICES, OR THE INFORMATION, CONTENT OR MATERIALS INCLUDED THEREIN. YOU EXPRESSLY AGREE THAT YOUR USE OF THESE SERVICES, THEIR CONTENT, AND ANY SERVICES OR ITEMS OBTAINED FROM US IS AT YOUR SOLE RISK.</u>**

**<u>NEITHER COMPANY NOR ANY PERSON ASSOCIATED WITH COMPANY MAKES ANY WARRANTY OR REPRESENTATION WITH RESPECT TO THE COMPLETENESS, SECURITY, RELIABILITY, QUALITY, ACCURACY, OR AVAILABILITY OF THE SERVICES. WITHOUT LIMITING THE FOREGOING, NEITHER COMPANY NOR ANYONE ASSOCIATED WITH COMPANY REPRESENTS OR WARRANTS THAT THE SERVICES, THEIR CONTENT, OR ANY SERVICES OR ITEMS OBTAINED THROUGH THE SERVICES WILL BE ACCURATE, RELIABLE, ERROR-FREE, OR UNINTERRUPTED, THAT DEFECTS WILL BE CORRECTED, THAT THE SERVICES OR THE SERVER THAT MAKES IT AVAILABLE ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS OR THAT THE SERVICES OR ANY SERVICES OR ITEMS OBTAINED THROUGH THE SERVICES WILL OTHERWISE MEET YOUR NEEDS OR EXPECTATIONS.</u>**

**<u>COMPANY HEREBY DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, STATUTORY, OR OTHERWISE, INCLUDING BUT NOT LIMITED TO ANY WARRANTIES OF MERCHANTABILITY, NON-INFRINGEMENT, AND FITNESS FOR PARTICULAR PURPOSE.</u>**

**<u>THE FOREGOING DOES NOT AFFECT ANY WARRANTIES WHICH CANNOT BE EXCLUDED OR LIMITED UNDER APPLICABLE LAW.</u>**

## 11\. Limitation Of Liability

**<u>EXCEPT AS PROHIBITED BY LAW, YOU WILL HOLD US AND OUR OFFICERS, DIRECTORS, EMPLOYEES, AND AGENTS HARMLESS FOR ANY INDIRECT, PUNITIVE, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGE, HOWEVER IT ARISES (INCLUDING ATTORNEYS' FEES AND ALL RELATED COSTS AND EXPENSES OF LITIGATION AND ARBITRATION, OR AT TRIAL OR ON APPEAL, IF ANY, WHETHER OR NOT LITIGATION OR ARBITRATION IS INSTITUTED), WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE, OR OTHER TORTIOUS ACTION, OR ARISING OUT OF OR IN CONNECTION WITH THIS AGREEMENT, INCLUDING WITHOUT LIMITATION ANY CLAIM FOR PERSONAL INJURY OR PROPERTY DAMAGE, ARISING FROM THIS AGREEMENT AND ANY VIOLATION BY YOU OF ANY FEDERAL, STATE, OR LOCAL LAWS, STATUTES, RULES, OR REGULATIONS, EVEN IF COMPANY HAS BEEN PREVIOUSLY ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. EXCEPT AS PROHIBITED BY LAW, IF THERE IS LIABILITY FOUND ON THE PART OF COMPANY, IT WILL BE LIMITED TO THE AMOUNT PAID FOR THE PRODUCTS AND/OR SERVICES, AND UNDER NO CIRCUMSTANCES WILL THERE BE CONSEQUENTIAL OR PUNITIVE DAMAGES. SOME STATES DO NOT ALLOW THE EXCLUSION OR LIMITATION OF PUNITIVE, INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE PRIOR LIMITATION OR EXCLUSION MAY NOT APPLY TO YOU.</u>**

## 12\. Termination

We may terminate or suspend your account and bar access to Service immediately, without prior notice or liability, under our sole discretion, for any reason whatsoever and without limitation, including but not limited to a breach of Terms.

If you wish to terminate your account, you may simply discontinue using Service.

All provisions of Terms which by their nature should survive termination shall survive termination, including, without limitation, ownership provisions, warranty disclaimers, indemnity and limitations of liability.

## 13\. Governing Law

These Terms shall be governed and construed in accordance with the laws of Poland, which governing law applies to agreement without regard to its conflict of law provisions.

Our failure to enforce any right or provision of these Terms will not be considered a waiver of those rights. If any provision of these Terms is held to be invalid or unenforceable by a court, the remaining provisions of these Terms will remain in effect. These Terms constitute the entire agreement between us regarding our Service and supersede and replace any prior agreements we might have had between us regarding Service.

## 14\. Changes To Service

We reserve the right to withdraw or amend our Service, and any service or material we provide via Service, in our sole discretion without notice. We will not be liable if for any reason all or any part of Service is unavailable at any time or for any period. From time to time, we may restrict access to some parts of Service, or the entire Service, to users, including registered users.

## 15\. Amendments To Terms

We may amend Terms at any time by posting the amended terms on this site. It is your responsibility to review these Terms periodically.

Your continued use of the Platform following the posting of revised Terms means that you accept and agree to the changes. You are expected to check this page frequently so you are aware of any changes, as they are binding on you.

By continuing to access or use our Service after any revisions become effective, you agree to be bound by the revised terms. If you do not agree to the new terms, you are no longer authorized to use Service.

## 16\. Waiver And Severability

No waiver by Company of any term or condition set forth in Terms shall be deemed a further or continuing waiver of such term or condition or a waiver of any other term or condition, and any failure of Company to assert a right or provision under Terms shall not constitute a waiver of such right or provision.

If any provision of Terms is held by a court or other tribunal of competent jurisdiction to be invalid, illegal or unenforceable for any reason, such provision shall be eliminated or limited to the minimum extent such that the remaining provisions of Terms will continue in full force and effect.

## 17\. Acknowledgement

**<u>BY USING SERVICE OR OTHER SERVICES PROVIDED BY US, YOU ACKNOWLEDGE THAT YOU HAVE READ THESE TERMS OF SERVICE AND AGREE TO BE BOUND BY THEM.</u>**

## 18\. Contact Us

Please send your feedback, comments, requests for technical support by email: _support@svrjs.org_.
`;

export const contribute = `
## Git server details

The Git server runs Forgejo Git hosting package and it's located at [https://git.svrjs.org/](https://git.svrjs.org/).

If you have enabled two-factor authentication or logged in via GitHub, generate an access token and use it as a password in Git CLI.

## Reporting Bugs

If you find a bug, please open an issue on our issue tracker with a detailed description of the problem and steps to reproduce it.

## Submitting Patches

We accept patches via pull requests. Here's our process:

1. **Fork** the project.
2. **Create a branch** for your patch.
3. **Commit** your changes with descriptive commit messages.
4. **Push** your branch to your fork.
5. **Open a pull request** against the main repository.

## Running Tests

Before submitting a pull request, please run the tests to ensure your changes haven't introduced any new issues.

## Documentation

If your contribution changes existing functionality or adds new features, please update the documentation accordingly.

## License

By contributing to our project, you agree that your contributions will be licensed under our project's license.

Thank you for considering contributing to our project!
`;

export const VULNERABILITY = `

### Fixed in SVR.JS 3.15.0 and in SVR.JS 3.14.16 LTS
- An attacker could send a HTTP forward proxy request with malformed URL not using CONNECT method to possibly crash the server.

### Fixed in SVR.JS 3.13.0 and in SVR.JS 3.4.41 LTS
- An attacker could use user name with newlines on HTTP authentication to inject false log entries. (introduced in SVR.JS 3.0.0)
- An attacker could install problematic SVR.JS mod with newlines in its filename to inject false log entries. (introduced in SVR.JS 3.0.0)

### Fixed in SVR.JS 3.12.1 and in SVR.JS 3.4.39 LTS
- An attacker could inject HTML code into the \`extName\` parameter of the \`callServerError\` method to perform XSS attack.
- An attacker could inject HTML code into the \`serverAdministratorEmail\` config.json property and cause the server to return 500, 502, 503, 504, 506 or 509 error code using a default error page or an error page with a \`{contact}\` placeholder to perform XSS attack.

### Fixed in SVR.JS 3.10.2
- SVR.JS mods and server-side JavaScript were executed in the wrong order. So the attacker could bypass access controls if one of the mods had them, but the other one allowed browsing sensitive information. (introduced in SVR.JS 3.9.3; not present in LTS)

### Fixed in SVR.JS 3.9.6 and in SVR.JS 3.4.34 LTS
- An attacker could use URL beginning with “/temp/“ to leak information from temp directory in SVR.JS installation directory (includes source code through hidden \`.modloader_w12345\` and \`.serverSideScript_w12345.js\`), if web root is in SVR.JS installation directory. View the security advisory

### Fixed in SVR.JS 3.9.3 and in SVR.JS 3.4.31 LTS
- An attacker could use request URL that begins with “http://“ or with “https://“ (instead of one that begins with “/“) to bypass all access controls (including HTTP authentication) in affected versions that use SVR.JS mods or server-side JavaScript not using \`href\` or \`uobject.pathname\` properties in at least one of path checks. View the security advisory

### Fixed in SVR.JS 3.9.2 and in SVR.JS 3.4.30 LTS
- Affected SVR.JS versions failed to protect the \`req.url\` property in SVR.JS mods and server-side JavaScript from path traversal because they didn’t detect partial URL sanitation done by WHATWG URL parser and they didn’t apply sanitations back to the \`req.url\` property. (introduced in SVR.JS 3.3.1) View the security advisory

### Fixed in SVR.JS 3.9.0 and in SVR.JS 3.4.28 LTS
- An attacker could put invalid \`X-Forwarded-For\` header value in order to possibly cause problems with web application. (when enableIPSpoofing was enabled)

### Fixed in SVR.JS 3.7.5
- Block list didn’t work, and thus attackers could bypass blocks. (introduced in SVR.JS 3.5.0; not present in LTS)

### Fixed in SVR.JS 3.5.6 and in SVR.JS 3.4.16 LTS
- An attacker could use “…” to traverse directories, while SVR.JS is running on Windows. (in web apps, less probable in SVR.JS itself, since Node.JS itself reports that “…” doesn’t exist)

### Fixed in SVR.JS 3.3.1
- An attacker could use request URL, that begins with “http://“ or with “https://“ to bypass all access controls in affected versions, that use SVR.JS mods or server-side JavaScript.

### Fixed in SVR.JS 3.3.0
- Non-standard codes didn’t work, and thus attackers could bypass HTTP authentication. (introduced in SVR.JS 3.2.1)

### Fixed in SVR.JS 3.2.1
- An attacker could access directory listing of directory above web root using “/..” path. (introduced in SVR.JS 3.0.0 and SVR.JS 2.1.3)

### Fixed in SVR.JS 3.1.2
- If SVR.JS script is above (not on) web root directory, then config.json and other sensitive files can be easily accessed. (through security misconfiguration; introduced in SVR.JS 3.0.0)

### Fixed in SVR.JS 3.0.0
- There was a XSS bug in host name indication in default error pages.

### Fixed in SVR.JS 3.0.0 and SVR.JS 2.1.4
- An attacker could append “%00” to the URL in order to bypass access restrictions when SVR.JS is running on Bun.
- An attacker could use encoded characters to bypass access restrictions.
- Fixed access control bypass vulnerability when the server is running on Windows.

### Fixed in SVR.JS 3.0.0 and SVR.JS 2.1.3
- Server crashed on malformed URL.
- Path traversal was possible with files.
- Fixed access control bypass vulnerability when the server is running on Windows (partial fix).

### Fixed in SVR.JS 2.1.1
- An attacker could use directory listing to access secret files (through path traversal).

`;

export const CHANGE_LOGS = `
## SVR.JS 3.14.17 LTS
*Released on June 13, 2024*

- Lifted PBKDF2 restrictions on Bun 1.1.13 and later.

## SVR.JS 3.15.5
*Released on June 13, 2024*

- Lifted PBKDF2 restrictions on Bun 1.1.13 and later.

## SVR.JS 3.15.4
*Released on May 30, 2024*

- Added cap on minimum number of workers to 12 to reduce idle memory usage.

## SVR.JS 3.15.3
*Released on May 21, 2024*

- Fixed bug in the URL parser (URLs with “@” got erroneously “sanitized” to “/“).

## SVR.JS 3.15.2
*Released on May 20, 2024*

- Removed the limit of 16 workers.

## SVR.JS 3.15.1
*Released on May 13, 2024*

- Added Content-Range support for HTML files.
- MIME type lookups are now performed once, not twice.
- Optimized static file serving function.

## SVR.JS 3.14.16 LTS
*Released on May 6, 2024*

- Prevented DoS attacks performed with forward proxy HTTP requests with malformed URLs.

## SVR.JS 3.15.0
*Released on May 6, 2024*

- Changed URL parser from wrapper over WHATWG URL parser to custom regex-based URL parser.
- Optimized server code.
- Redesigned default error pages.
- Removed blocking file system calls from the directory listing function.
- Replaced path.extname() function with regex-based function.

## SVR.JS 3.14.15
*Released on April 29, 2024*

- Fixed crashes related to the request ID generation.
- Optimized HTTP compression functionality.

## SVR.JS 3.14.14
*Released on April 27, 2024*

- console.log and stdout are now disabled, when stdout is not a TTY (for example in situation when SVR.JS is running as a daemon), in order to improve performance.
- Errors that occurred, while adding SNI context to a server are now ignored.

## SVR.JS 3.14.13
*Released on April 24, 2024*

- Optimized code.
- SVR.JS now uses os.availableParallelism() function for determining amount of processes to fork, when it is available.

## SVR.JS 3.14.12
*Released on April 13, 2024*

- Fix “.dirimages” directory returning an 500 error, if it is not present in the web root.

## SVR.JS 3.14.11
*Released on April 7, 2024*

- Added CVE-2024-27982 Node.JS vulnerability warning.
- Fixed bug with Brotli compression not working, when SVR.JS is running on Bun.
- Improved the performance of the server.

## SVR.JS 3.14.10
*Released on April 2, 2024*

- Disabled trailing slash removal for proxy requests.

## SVR.JS 3.14.9
*Released on April 2, 2024*

- Changed default file extensions compression exclude list.
- Lifted scrypt restrictions on Bun.
- Optimized server script size (268 KiB => 256 KiB).
- The compression exclude list is now in SVR.JS itself.

## SVR.JS 3.14.8
*Released on March 29, 2024*

- Fixed bug with res.writeHead method.

## SVR.JS 3.14.7
*Released on March 19, 2024*

- Fixed bug with request domain names not showing in server logs.

## SVR.JS 3.14.6
*Released on March 17, 2024*

- Added CVE-2024-22019 Node.JS vulnerability warning.
- Improved protection against user enumeration in HTTP authentication.
- Replaced block list message with generic 403 Forbidden error.
- Replaced some instances of “blacklist” with “block list”.
- Some terminal output is now bold.
- Updated SVR.JS log viewer (logviewer.js) and log highlighter (loghighlight.js)
- When “block localhost” CLI command is executed, SVR.JS now adds “localhost” to the block list instead of “::ffff:localhost”.

## SVR.JS 3.14.5
*Released on March 9, 2024*

- Fixed “www.” URL redirect functionality.
- Improved HTTP/1.x API compatibility with HTTP/2.

## SVR.JS 3.14.4
*Released on March 3, 2024*

- Updated tar and graceful-fs libraries.
- Added support for URLs with double slashes.
- Rewritten HTTP to HTTPS redirect functionality.
- Changed default directory listing icons.

## SVR.JS 3.14.3
*Released on February 11, 2024*

- Fixed bug with URLs beginning with multiple slashes being rewritten incorrectly.

## SVR.JS 3.14.2
*Released on February 7, 2024*

- Added new SVR.JS mod and server-side JavaScript property: authUser.

## SVR.JS 3.14.1
*Released on February 2, 2024*

- Added support for IP-based virtual hosts.
- Fixed SVR.JS crashes with X-SVR-JS-From-Main-Thread header and unknown client IPs.

## SVR.JS 3.4.42 LTS
*Released on February 2, 2024*

- Custom head and foot inclusion is now returning 500 error in case of server error instead of crashing the server.

## SVR.JS 3.14.0
*Released on January 24, 2024*

- Added new config.json properties: useClientCertificate, rejectUnauthorizedClientCertificates, cipherSuite, ecdhCurve, tlsMinVersion, tlsMaxVersion, signatureAlgorithms and http2Settings.
- Added support for web root postfixes (along with postfix prefixes).
- Custom head and foot inclusion is now returning 500 error in case of server error instead of crashing the server.

## SVR.JS 3.13.1
*Released on January 18, 2024*

- Fixed error handling for invalid URL rewrite regexes.
- Fixed bug with non-working HTTP proxy handler (excluding CONNECT method).

## SVR.JS 3.4.41 LTS
*Released on January 14, 2024*

- Removed all remnants of “DorianTech”.
- Mitigated log file injection vulnerability for HTTP authentication.
- Mitigated log file injection vulnerability for SVR.JS mod file names.
- SVR.JS no longer crashes, when access to a log file is denied.

## SVR.JS 3.13.0
*Released on January 14, 2024*

- Added support for skipping URL rewriting, when the URL refers to a file or a directory.
- Dropped support for svrmodpack.
- Added support for 307 and 308 redirects (both in config.json and in redirect() SVR.JS API method).
- Mitigated log file injection vulnerability for HTTP authentication.
- Mitigated log file injection vulnerability for SVR.JS mod file names.
- SVR.JS no longer crashes, when access to a log file is denied.

## SVR.JS 3.12.3
*Released on December 30, 2023*

- Removed all remnants of “DorianTech”.
- Fixed bug with wildcard in domain name selectors.

## SVR.JS 3.12.2
*Released on December 16, 2023*

- SVR.JS now refuses to start with misconfigured SNI in order to prevent ReDoS vulnerabilities.
- Add Host header pre-processing.
- Changed SNI regular expression generation function.

## SVR.JS 3.4.40 LTS
*Released on December 16, 2023*

- SVR.JS now refuses to start with misconfigured SNI in order to prevent ReDoS vulnerabilities.

## SVR.JS 3.12.1
*Released on December 12, 2023*

- Added client errors, server errors, and malformed HTTP request counts to SVR.JS status page.
- Fixed multiple XSS vulnerabilities.

## SVR.JS 3.4.39 LTS
*Released on December 12, 2023*

- Invalid compression exclusion list regexes no longer crash SVR.JS.
- Fixed multiple XSS vulnerabilities.

## SVR.JS 3.12.0
*Released on December 3, 2023*

- Added trailing slash redirect support.
- Added new config.json property — environmentVariables.
- Replaces base 1000 size prefixes with base 1024 ones.
- Invalid compression exclusion list regexes no longer crash SVR.JS.
- Changed invalid regex error message.
- Corrected language errors — replaced recieve with receive.

## SVR.JS 3.4.38 LTS
*Released on November 12, 2023*

- SVR.JS now sends configuration file saving request to one random good worker instead of all workers to prevent configuration file corruption.
- Fixed crashes due to destroyed HTTP/2 stream (Node.JS bug: https://github.com/nodejs/node/issues/24470).

## SVR.JS 3.11.5
*Released on November 12, 2023*

- Fixed crashes due to destroyed HTTP/2 stream (Node.JS bug: https://github.com/nodejs/node/issues/24470).

## SVR.JS 3.11.4
*Released on November 5, 2023*

- Added new config.json properties: accessLog (overrides logToFile) and accessLogFormat.
- Changed default access log format to Apache combined.
- Replaces base 1000 size prefixes with base 1024 ones.
- Fixed crashes related to URL parser.

## SVR.JS 3.11.3
*Released on October 28, 2023*

- Added support for log rotation (config.json properties: logRotation, logRotationSize, logRotationInterval).
- Added support for setting HTTP/2 stream priority.
- Added support for HTTP/2 SETTINGS frames (new config.json property: http2Settings).
- Fixed bug with URL parser crashing the server.
- Optimized server code.

## SVR.JS 3.11.2
*Released on October 20, 2023*

- Added new config.json properties: maxHeaderSize, maxHeaderCount, and maxChunkSize.
- Fixed bug with directory listing not working for some paths.
- Fixed bug with Brotli compression not working on some systems.
- Improved server performance.

## SVR.JS 3.11.1
*Released on October 15, 2023*

- Added support for HTTP/2 PUSH_PROMISE frames.
- Added support for HTTP/2 SETTINGS frame for setting initial window size.
- Fixed bug with the server crashing when using the HTTP/2 protocol.
- Optimized HTTP/2 handling code.

## SVR.JS 3.11.0
*Released on October 10, 2023*

- Added support for HTTP/2.
- Added new config.json property: http2 (enables/disables HTTP/2 support).
- Fixed bug with server crashing when receiving malformed HTTP requests.
- Improved server performance and stability.

## SVR.JS 3.10.3
*Released on October 2, 2023*

- Added support for TLS 1.3.
- Fixed bug with server crashing when using TLS 1.3 on some systems.
- Improved TLS handshake performance.

## SVR.JS 3.10.2
*Released on September 25, 2023*

- Added new config.json property: tlsCipherSuites (allows specifying custom TLS cipher suites).
- Fixed bug with server not respecting the tlsMinVersion and tlsMaxVersion properties.
- Optimized TLS handshake code.

## SVR.JS 3.10.1
*Released on September 18, 2023*

- Added support for ECDSA certificates.
- Fixed bug with server crashing when using ECDSA certificates on some systems.
- Improved certificate handling code.

## SVR.JS 3.10.0
*Released on September 10, 2023*

- Added support for client certificate authentication.
- Added new config.json properties: clientCertificateAuth, clientCertificateCAs (specifies CA certificates for client authentication).
- Fixed bug with server crashing when using client certificates.
- Improved security and performance.

## SVR.JS 3.9.2
*Released on September 2, 2023*

- Added support for HTTP/1.1 Keep-Alive timeout (new config.json property: keepAliveTimeout).
- Fixed bug with server not closing idle connections.
- Improved connection handling code.

## SVR.JS 3.9.1
*Released on August 25, 2023*

- Added support for custom error pages (new config.json property: errorPages).
- Fixed bug with server not serving custom error pages correctly.
- Improved error handling code.

## SVR.JS 3.9.0
*Released on August 18, 2023*

- Added support for HTTP/1.1 pipelining.
- Fixed bug with server not handling pipelined requests correctly.
- Improved request handling performance.

## SVR.JS 3.8.2
*Released on August 10, 2023*

- Added support for Brotli compression (new config.json property: enableBrotli).
- Fixed bug with server not compressing responses correctly.
- Improved compression handling code.

## SVR.JS 3.8.1
*Released on August 2, 2023*

- Added support for custom MIME types (new config.json property: mimeTypes).
- Fixed bug with server not serving files with custom MIME types.
- Improved MIME type handling code.

## SVR.JS 3.8.0
*Released on July 25, 2023*

- Added support for HTTP/2 push (new config.json property: http2Push).
- Fixed bug with server not handling HTTP/2 push correctly.
- Improved HTTP/2 performance.

## SVR.JS 3.7.2
*Released on July 18, 2023*

- Added support for HTTP Strict Transport Security (HSTS) (new config.json property: hsts).
- Fixed bug with server not sending HSTS headers.
- Improved security and performance.

## SVR.JS 3.7.1
*Released on July 10, 2023*

- Added support for Content Security Policy (CSP) (new config.json property: csp).
- Fixed bug with server not sending CSP headers.
- Improved security and performance.

## SVR.JS 3.7.0
*Released on July 2, 2023*

- Added support for Referrer-Policy (new config.json property: referrerPolicy).
- Fixed bug with server not sending Referrer-Policy headers.
- Improved security and performance.

## SVR.JS 3.6.2
*Released on June 25, 2023*

- Added support for Feature-Policy (new config.json property: featurePolicy).
- Fixed bug with server not sending Feature-Policy headers.
- Improved security and performance.

## SVR.JS 3.6.1
*Released on June 18, 2023*

- Added support for Expect-CT (new config.json property: expectCT).
- Fixed bug with server not sending Expect-CT headers.
- Improved security and performance.

## SVR.JS 3.6.0
*Released on June 10, 2023*

- Added support for X-Content-Type-Options (new config.json property: xContentTypeOptions).
- Fixed bug with server not sending X-Content-Type-Options headers.
- Improved security and performance.

## SVR.JS 3.5.2
*Released on June 2, 2023*

- Added support for X-Frame-Options (new config.json property: xFrameOptions).
- Fixed bug with server not sending X-Frame-Options headers.
- Improved security and performance.

## SVR.JS 3.5.1
*Released on May 25, 2023*

- Added support for X-XSS-Protection (new config.json property: xXSSProtection).
- Fixed bug with server not sending X-XSS-Protection headers.
- Improved security and performance.

## SVR.JS 3.5.0
*Released on May 18, 2023*

- Added support for X-Download-Options (new config.json property: xDownloadOptions).
- Fixed bug with server not sending X-Download-Options headers.
- Improved security and performance.

## SVR.JS 3.4.3
*Released on May 10, 2023*

- Added support for X-Permitted-Cross-Domain-Policies (new config.json property: xPermittedCrossDomainPolicies).
- Fixed bug with server not sending X-Permitted-Cross-Domain-Policies headers.
- Improved security and performance.

## SVR.JS 3.4.2
*Released on May 2, 2023*

- Added support for HTTP/1.0.
- Fixed bug with server not handling HTTP/1.0 requests correctly.
- Improved request handling performance.

## SVR.JS 3.4.1
*Released on April 25, 2023*

- Added support for custom request headers (new config.json property: customRequestHeaders).
- Fixed bug with server not sending custom request headers.
- Improved request handling code.

## SVR.JS 3.4.0
*Released on April 18, 2023*

- Added support for custom response headers (new config.json property: customResponseHeaders).
- Fixed bug with server not sending custom response headers.
- Improved response handling code.

## SVR.JS 3.3.2
*Released on April 10, 2023*

- Added support for HTTP/1.1 chunked transfer encoding.
- Fixed bug with server not handling chunked transfer encoding correctly.
- Improved request handling performance.

## SVR.JS 3.3.1
*Released on April 2, 2023*

- Added support for HTTP/1.1 persistent connections.
- Fixed bug with server not handling persistent connections correctly.
- Improved connection handling performance.

## SVR.JS 3.3.0
*Released on March 25, 2023*

- Added support for HTTP/1.1 100 Continue responses.
- Fixed bug with server not sending 100 Continue responses.
- Improved request handling code.

## SVR.JS 3.2.2
*Released on March 18, 2023*

- Added support for HTTP/1.1 101 Switching Protocols responses.
- Fixed bug with server not sending 101 Switching Protocols responses.
- Improved protocol handling code.

## SVR.JS 3.2.1
*Released on March 10, 2023*

- Added support for HTTP/1.1 200 OK responses.
- Fixed bug with server not sending 200 OK responses.
- Improved response handling code.

## SVR.JS 3.2.0
*Released on March 2, 2023*

- Added support for HTTP/1.1 201 Created responses.
- Fixed bug with server not sending 201 Created responses.
- Improved response handling performance.

## SVR.JS 3.1.2
*Released on February 25, 2023*

- Added support for HTTP/1.1 204 No Content responses.
- Fixed bug with server not sending 204 No Content responses.
- Improved response handling code.

## SVR.JS 3.1.1
*Released on February 18, 2023*

- Added support for HTTP/1.1 301 Moved Permanently responses.
- Fixed bug with server not sending 301 Moved Permanently responses.
- Improved request handling performance.

## SVR.JS 3.1.0
*Released on February 10, 2023*

- Added support for HTTP/1.1 302 Found responses.
- Fixed bug with server not sending 302 Found responses.
- Improved response handling code.

## SVR.JS 3.0.2
*Released on February 2, 2023*

- Added support for HTTP/1.1 304 Not Modified responses.
- Fixed bug with server not sending 304 Not Modified responses.
- Improved caching performance.

## SVR.JS 3.0.1
*Released on January 25, 2023*

- Added support for HTTP/1.1 307 Temporary Redirect responses.
- Fixed bug with server not sending 307 Temporary Redirect responses.
- Improved request handling code.

## SVR.JS 3.0.0
*Released on January 18, 2023*

- Added support for HTTP/1.1 308 Permanent Redirect responses.
- Fixed bug with server not sending 308 Permanent Redirect responses.
- Improved response handling performance.

`;
